###############################################################

#                   Authelia configuration                    #

###############################################################

host: 0.0.0.0
port: 9091
log_level: warn

#default-redirection-url
default_redirection_url: https://authelia.example.com

# Add the default OTP configuration
totp:  
  issuer: authelia.com  
  period: 30  
  skew: 1

authentication_backend:  
  file:    
    path: /config/users_database.yml    
    password:      
      algorithm: argon2id      
      iterations: 1      
      salt_length: 16      
      parallelism: 8      
      memory: 512 # blocks this much of the RAM. Tune this.

access_control:  
  default_policy: deny  
  rules:    
    - domain: n8n.example.com
      resources:
    - "^/webhook/.*$"
      policy: bypass
    - domain: authelia.example.com
      policy: bypass
    - domain: matrix.example.com
      resources:
      - "^/admin.*$"
      policy: two_factor
    - domain: matrix.example.com
      policy: bypass
    - domain: element.example.com
      policy: bypass
    - domain: jitsi.example.com
      policy: bypass
    - domain: dimension.example.com
      policy: bypass
    - domain: gotify.example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: gotify.example.com
      policy: two_factor
    - domain: pwndrop.example.com
      resources:
      - "^/pwndrop.*$"
      policy: two_factor
    - domain: pwndrop.example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: pwndrop.example.com
      policy: two_factor
    - domain: example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: rssbridge.example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: rssbridge.example.com
      policy: two_factor
    - domain: rsshub.example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: rsshub.example.com
      policy: two_factor  
    - domain: ktn.example.com
      resources:
      - "^/.+$"
      policy: bypass
    - domain: ktn.example.com
      policy: two_factor  
    - domain: example.com
      policy: two_factor
    - domain: "*.example.com"
      policy: two_factor

session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.com # Should match whatever your root protected domain is
  redis:    
    host: redis    
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: mariadb
    port: 3306
    database: DB
    username: DBUSER

notifier:
  smtp:
    username: SMTP_USERNAME
    host: SMTP_HOST
    port: 587 # Or 465
    sender: SENDER_EMAIL
